name: Build palera1n

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dependencies
        run: |
          cd src
          curl -LOOO https://cdn.discordapp.com/attachments/672628720497852459/1064954768021274694/checkra1n-kpf-pongo https://cdn.discordapp.com/attachments/672628720497852459/1065189871251111966/binpack.dmg https://cdn.discordapp.com/attachments/672628720497852459/1065189871636983848/ramdisk.dmg
          cd ..
          curl -LO https://cdn.discordapp.com/attachments/672628720497852459/1064948547268661248/dep_root.tgz
          tar xf dep_root.tgz
          make -j5 download-checkra1n

      - name: Build
        run: |
          make -j$(sysctl -n hw.ncpu) macos-dist

      - name: Upload macOS universal build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: palera1n-macOS
          path: palera1n-macos

      - name: Upload macOS x86_64 build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: palera1n-macOS (x86_64)
          path: palera1n-x86_64

      - name: Upload macOS arm64 build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: palera1n-macOS (arm64)
          path: palera1n-arm64

      - name: Upload macOS universal debug symbols
        uses: actions/upload-artifact@v2
        with:
          name: palera1n-macos.dSYM
          path: palera1n-macos.dSYM
